### PR TITLE
Devise installed, Devise view installed

### PR DESCRIPTION
**Pull request by KojoSwiss**
Devise installed. I hope it is okay

### CODE REVIEW

**Comment by ericblandet** [comment]
Hey Ben !
looks nice! did you add the right columns in the user model and db?

**Comment by KojoSwiss** [comment]
Screenshot 2020-11-23 at 14 57 32

**Comment by ericblandet** [comment]
can you add the validations on the model please?

**Review by Simon-Busch — COMMENTED** [review]
All right seems to be ok for me.

**Comment by KojoSwiss** [comment]
Devise already takes care of the validations :)

**Comment by ericblandet** [comment]
good job !

**Pull request merged**
